services:
  backend:
    build:
      context: ./ # Aponta para o backend (onde está o docker-compose)
    container_name: BJLogbackend
    image: b-j-log-backend
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    env_file:
      - .env # Variáveis de ambiente para o backend
