services:
  backend:
    build:
      context: ./ # Aponta para o backend (onde está o docker-compose)
    container_name: BJLogbackend
    image: b-j-log-backend
    ports:
      - "8080:5000"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
      - .env.production
    networks:
      - bjlog_network

networks:
  bjlog_network:
    external: true
