services:
  backend:
    build:
      context: ./ # Aponta para o backend (onde está o docker-compose)
    container_name: BJLogbackend
    image: b-j-log-backend
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    env_file:
      - .env # Variáveis de ambiente para o backend

  frontend:
    build:
      context: ../B-J-Log-frontend # Aponta para o repositório/clonagem do frontend
    container_name: BJLogfrontend
    image: b-j-log-frontend
    ports:
      - "8081:3000"
    volumes:
      - ../B-J-Log-frontend:/app
