"""criação tabela terceiros_integracao e adição da fk na tabela token_acesso

Revision ID: 39d8e3bd2922
Revises: 261a4368fda8
Create Date: 2024-09-15 20:02:06.289728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d8e3bd2922'
down_revision = '261a4368fda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terceiros_integracao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('token_acesso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terceiro_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'terceiros_integracao', ['terceiro_id'], ['id'])
        batch_op.drop_column('sistema_nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_acesso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sistema_nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint("token_acesso_terceiro_id_fkey", type_="foreignkey")
        batch_op.drop_column('terceiro_id')

    op.drop_table('terceiros_integracao')
    # ### end Alembic commands ###
