"""ajuste na tabela Empresa

Revision ID: 65d2d886b26a
Revises: d0f4098bdc72
Create Date: 2024-09-22 21:39:00.193482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65d2d886b26a'
down_revision = 'd0f4098bdc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regime_tributario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_regime_tributario', sa.Integer(), nullable=False))
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('inscricao_estadual',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('inscricao_municipal',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('setor_atividade',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('data_fundacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('logotipo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('observacoes',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id_matriz',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'regime_tributario', ['id_regime_tributario'], ['id'])
        batch_op.drop_column('regime_tributario')
        batch_op.drop_column('porte_empresa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('porte_empresa', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('regime_tributario', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_matriz',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('observacoes',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('logotipo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('data_fundacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('setor_atividade',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('inscricao_municipal',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('inscricao_estadual',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('id_regime_tributario')

    op.drop_table('regime_tributario')
    # ### end Alembic commands ###
