"""Adicionando coluna de Senha no usuário

Revision ID: a0bbed1af41d
Revises: eefc0f4337ed
Create Date: 2024-09-20 00:30:25.326962

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0bbed1af41d"
down_revision = "eefc0f4337ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usuario", schema=None) as batch_op:
        batch_op.add_column(sa.Column("password", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usuario", schema=None) as batch_op:
        batch_op.drop_column("password")

    # ### end Alembic commands ###
