"""criação de novas tabelas

Revision ID: d0f4098bdc72
Revises: ced52a593f10
Create Date: 2024-09-22 20:44:16.164023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f4098bdc72'
down_revision = 'ced52a593f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contato',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contato_principal', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=False),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=False),
    sa.Column('inscricao_municipal', sa.String(length=20), nullable=False),
    sa.Column('regime_tributario', sa.String(length=50), nullable=False),
    sa.Column('setor_atividade', sa.String(length=100), nullable=False),
    sa.Column('data_fundacao', sa.DateTime(), nullable=False),
    sa.Column('porte_empresa', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('logotipo', sa.String(length=255), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=False),
    sa.Column('id_matriz', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_matriz'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa_contato',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_contato', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_contato'], ['contato.id'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa_endereco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_endereco', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['id_endereco'], ['endereco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_empresa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_empresa')
    op.drop_table('empresa_endereco')
    op.drop_table('empresa_contato')
    op.drop_table('endereco')
    op.drop_table('empresa')
    op.drop_table('contato')
    # ### end Alembic commands ###
