"""Adicionando Unique ao nome da tabela de token

Revision ID: e278a8f715b5
Revises: 631495f154c2
Create Date: 2024-09-20 13:27:27.629328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e278a8f715b5'
down_revision = '631495f154c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_authentication', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nome'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_authentication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
